[package]
name = "telegram-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
color-eyre = "0.6.3"
reqwest = { version = "0.12.12", features = ["json"] }
lazy_static = "1.5.0"
serde = "1.0.217"
